[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-kiceos-gnu.json"

[target.x86_64-unknown-kiceos-gnu.json]
runner = "qemu-system-x86_64 -drive format=raw,file=kernel.bin"
